import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import { IntroMainContent, NavigationBar } from "../components";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Aditya Kumar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen">
        <NavigationBar />
        <div className="container mx-auto pt-10 flex gap-4 justify-center items-center h-screen">
          <IntroMainContent />
        </div>
      </main>
    </>
  );
}
